class Main {

    public static int solver() {
        // Parse line by line through input.txt

        // Convert from String to Integer

        // Iterate through the String with pointers such as max_battery
        // max_battery will always be the 2nd digit of the result with 9 being the max
        // can break through the loop if we find two 9's

        // Combine the two digits together and assign them to max_battery (maybe have helper function for this)

        // Add max_battery to result
    }

    public static void main() {

    }
}