import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;

class Main {

    public static long solver() {
        // inputs from input.txt are int that are read vertically

        // they say right to left but left to right is the same process

    }


    
    public static void main(String[] args) {
        System.out.println(solver());
    }
}
